### ISSUE TITLE
Only have one 'Purchase Link Shade' open at a time.

### ISSUE THREAD

**Issue by cklosowski** [SDavisMedia/vendd#11]
Currently if you click a `+` of a purchase link, and then click the `+` of another product, you can end up with two open purchase links. We should close any open purchase links when one is clicked:

![image](https://cloud.githubusercontent.com/assets/1390124/7657531/6c9a8550-fae7-11e4-8c79-15e36d82c404.png)

**Comment by SDavisMedia** [comment]
:+1:
