### ISSUE TITLE
First implementation of Software Licensing not working

### ISSUE THREAD

**Issue by SDavisMedia** [SDavisMedia/vendd#13]
@cklosowski @pippinsplugins I could use a second set of eyes here. Not sure what I'm missing... I didn't change much of the licensing code. I tested from the same host site with the sample theme and nothing changed but the very basics and still ended up with "License keys do not match." 

If you wouldn't mind taking a look/testing, that would be great!

**Comment by SDavisMedia** [comment]
Updater Files: https://github.com/SDavisMedia/vendd/tree/master/inc/admin/updater

**Comment by pippinsplugins** [comment]
A few things:

1. Add `'url' => home_url()` here: https://github.com/SDavisMedia/vendd/blob/master/inc/admin/updater/theme-updater-admin.php#L298 and https://github.com/SDavisMedia/vendd/blob/master/inc/admin/updater/theme-updater-admin.php#L325
2. You're calling the EDD site but there is no `Vendd` product or license keys.

**Comment by SDavisMedia** [comment]
@pippinsplugins 

1. I'll get that added. If it's needed, we should update the SL sample code.

2. I'm not testing with the EDD site details, of course. I change them before testing. That's just what I have in there for the repo.

**Comment by SDavisMedia** [comment]
@mindctrl you mind testing this on a live site for me and seeing if it works for you? All you should need to change is the remote_api_url in theme-updater.php and name the download Vendd.

**Comment by mindctrl** [comment]
@sdavismedia :+1: will test this evening.

**Comment by SDavisMedia** [comment]
Thanks, boss!

**Comment by mindctrl** [comment]
@SDavisMedia pushed a fix to issue/13 branch. `esc_url_raw` is needed in `get_api_response`. I had opened a PR for in the SL repo after you had already started Vendd I think. Note that since then a PR for `wp_remote_post` has been merged. I haven't tested that one yet.

**Comment by SDavisMedia** [comment]
You're the freakin' man, @mindctrl. All good now. Thanks!
