### ISSUE TITLE
Undefined indexes on customize screen before settings are saved

### ISSUE THREAD

**Issue by pippinsplugins** [SDavisMedia/vendd#18]
Upon first activation, visiting the Customize screen shows these:

Notice: Undefined index: checkout_color in /Users/pippinwilliamson/Sites/trunk/wp-content/themes/vendd/inc/customizer.php on line 317

Notice: Undefined variable: edd_button_color_hex in /Users/pippinwilliamson/Sites/trunk/wp-content/themes/vendd/inc/customizer.php on line 344

**Comment by pippinsplugins** [comment]
Ah, this is actually due to EDD style options not being saved.

**Comment by SDavisMedia** [comment]
Thank you, sir!
