### ISSUE TITLE
AJAXify the header checkout button

### ISSUE THREAD

**Issue by SDavisMedia** [SDavisMedia/vendd#2]
Because that's what all the cool kids are doing. The price should adjust when items are added to or removed from the cart.

**Comment by mindctrl** [comment]
@SDavisMedia @cklosowski I did this in another branch before looking to see if there was an issue for it. Found this before opening an issue pushing it. Check this out and see if it needs anything else.

**Comment by SDavisMedia** [comment]
@mindctrl That's golden! Works like a charm. Thanks, boss!
