### ISSUE TITLE
Style EDD and FES shortcodes

### ISSUE THREAD

**Issue by SDavisMedia** [SDavisMedia/vendd#20]
Forgot about this. I need to go through and check EDD/FES login and registration forms. Maybe even add a "focus" page template for simple shortcode display like that.... full header, single/centered content column, etc.

**Comment by SDavisMedia** [comment]
Vendor dashboard when not logged in: 

![screen shot 2015-05-17 at 5 54 25 pm](https://cloud.githubusercontent.com/assets/2359131/7673008/d20f7440-fcbd-11e4-95e0-35baf2ba8a1b.png)

More to come...

**Comment by SDavisMedia** [comment]
So many FES shortcomings here. I can't even get my hands (my CSS selectors) on some of this stuff. :unamused:

**Comment by mindctrl** [comment]
@SDavisMedia anything in particular?

**Comment by SDavisMedia** [comment]
An example would be the `[fes_login_registration_form]` shortcode. You can't target the table it's in. I have some general table styling in Vendd that's applying to the shortcode but I can't target it because it has no IDs classes. 

What I'm actually doing is going through every single EDD and FES shortcode to make sure it looks okay if a user puts it on the simplest of pages. The one I mentioned above just happens to be the first I've tried.

**Comment by SDavisMedia** [comment]
I'm considering making another page template... something along the longs of a "Focus" template. It would be simple... full header, full footer, single content column about 722px wide... centered. It would be perfect for login and registration forms. If I go that route, I can control the content wrapping div and give it a class so the generic form tables could be styled. This means it's best that 1) users don't use any other regular tables on that page template and 2) all users are encouraged to use the templates for displaying the shortcodes.
