### ISSUE TITLE
Add default option fallbacks for get_theme_mod calls

### ISSUE THREAD

**Issue by mindctrl** [SDavisMedia/vendd#22]
Example: In `content/content-single.php` line 21, there's no default option passed to the `get_theme_mod` call for `vendd_single_featured_image`, so it doesn't show the featured image on single posts by default without saving the options first. Customizer default indicates it will be shown, and actually does when customizer is invoked, but not on front end.

This would fix it:
`if ( has_post_thumbnail() && 1 == get_theme_mod( 'vendd_single_featured_image', 1 ) ) :`

There might be others. I can do a PR if you want. Just making notes as I go.

**Comment by SDavisMedia** [comment]
Sweeeet post all the notes you'd like. PRs are definitely welcome but not expected. So if you post issues, I have no problem going after them.

**Comment by SDavisMedia** [comment]
Perfect fix. I'll go through check all the other theme options and push the changes myself.

**Comment by SDavisMedia** [comment]
Should be all good here. :+1:
