### ISSUE TITLE
Download sidebar prints empty markup for contact methods

### ISSUE THREAD

**Issue by mindctrl** [SDavisMedia/vendd#27]
If an author profile doesn't have any contact methods configured, there's an empty list item and div printed that leave a little empty box. http://cl.ly/image/2a2Z1Q3X0K0D

The markup is wrapped in `<?php if ( '' != $social_profiles ) { ?>` but that'll always be true because the `$social_profiles` array is defined above.

**Comment by SDavisMedia** [comment]
Wow... that's some dumb a** logic. :flushed: I must have been drinking beer that night. Easy fix.
