### ISSUE TITLE
Empty cart message: only do_shortcode in the checkout?

### ISSUE THREAD

**Issue by mindctrl** [SDavisMedia/vendd#29]
When the cart is empty, the `do_shortcode` runs to suggest some products (https://github.com/SDavisMedia/vendd/blob/master/inc/edd-functions.php#L69). I noticed this is also being output in the cart widget in the sidebar but hidden with CSS. What do you think about checking `edd_is_checkout` and only running `do_shortcode` if it's the checkout page?

**Comment by SDavisMedia** [comment]
Yup! We're working on that here: https://github.com/SDavisMedia/vendd/issues/14

**Comment by mindctrl** [comment]
Nice. I missed that one.
