### ISSUE TITLE
Improve and simplify the JS

### ISSUE THREAD

**Issue by mindctrl** [SDavisMedia/vendd#31]
- Wrap it in a document ready check.

- Simplify the class and slide toggling.

PR incoming.

**Comment by SDavisMedia** [comment]
@mindctrl I don't see anything wrong with the changes at all. I tested all the JS features and all is well. Gonna merge.

**Comment by mindctrl** [comment]
@SDavisMedia for some reason I thought body was cached automatically, but it's not. So adding a minor improvement here.

**Comment by SDavisMedia** [comment]
Lol I'm trusting you in this area, man. I don't write JS. Merged! :+1:

**Comment by mindctrl** [comment]
I'm not a JS expert for sure, but I did do some testing and a some reading beforehand. :laughing:
