### ISSUE TITLE
slide toggle theme customizer control descriptions

### ISSUE THREAD

**Issue by SDavisMedia** [SDavisMedia/vendd#40]
Here's the customizer with its awesome descriptions:

![screen shot 2015-05-19 at 5 29 13 pm](https://cloud.githubusercontent.com/assets/2359131/7716827/b2f7f7f4-fe4c-11e4-9701-fa1dfdf94411.png)

I want to add a little question mark right after each control that toggles the display of the description.

**Comment by mindctrl** [comment]
I think you can use the `customize_controls_enqueue_scripts` hook to add some custom scripts/styles here.

**Comment by SDavisMedia** [comment]
@mindctrl Absolutely. I'll toss it in the customizer.php down there with `customize_controls_print_styles`.

**Comment by SDavisMedia** [comment]
For reference: https://codex.wordpress.org/Plugin_API/Action_Reference/customize_controls_enqueue_scripts

**Comment by SDavisMedia** [comment]
I really like this. 
![2015-05-21 at 11 33 pm](https://cloud.githubusercontent.com/assets/2359131/7764138/d089e860-0011-11e5-8552-5c5cdbfcefee.png)

**Comment by mindctrl** [comment]
Slick!
