### ISSUE TITLE
Integrate Simple Notices

### ISSUE THREAD

**Issue by SDavisMedia** [SDavisMedia/vendd#7]
Get the Pro version from Pippin. All the free version needs is...

```php
remove_action( 'wp_footer', 'pippin_display_notice' ); 
add_action( 'announcement_template_hook', 'pippin_display_notice' );
```

A quick `do_action()` in the `content-announcement.php` file is needed. Also override the CSS. Also check the customizer logic once the new integration is made. Also stop saying also.

https://pippinsplugins.com/simple-notices-plugin/

**Comment by sdavis2702** [comment]
Things to consider:

- [ ] Whether or not a notice is Active (Pro)
- [ ] Meta box options built into both levels of the plugin

**Comment by SDavisMedia** [comment]
Dropped support for Simple Notices, free and Pro.
